In [1]:
import numpy as np
import matplotlib.pyplot as plt

In [41]:
f=lambda x: np.exp(-((x[0]*x[1])**2+x[0]**2+x[1]**2-8*x[0]-8*x[1])/2) # Esta función de densidad conjunta es la vista en clase, pero chequen que no tiene ninguna constante c. 

In [39]:
#La función simuladora, donde N es la cantidad de variables que va a generar, contando el quemado;el valor inicial que lo
#pueden modificar, el periodo de quemado que tiene que ser menor que N porque si no truena, y la función de densidad a simular. 

#Chequen cómo lo que está adentro del for es el algoritmo que vimos en clase; el algoritmo sólo va a devolver las variables
#aleatorias que salgan DESPUÉS del periodo de quemado. 
def genf2d(N,a=1,valorinicial=np.array([0,0]),burn=1000, f=lambda x: np.exp(-((x[0]*x[1])**2+x[0]**2+x[1]**2-8*x[0]-8*x[1])/2) ):
    Variable=[]
    X=valorinicial
    for i in range(0,N):
        Z=a*np.random.normal(size=2)
        C=X+Z
        print([c for c in C])
        alpha=min( (f(C)/f(X)), 1  )
        U=np.random.uniform(size=1)[0]
        if U<alpha:
            X=C
        if i>=burn:
            Variable.append(X)
    return Variable
        
    
    

In [40]:
#Un ejemplo para simular 1000 variables aleatorias de f: 
genf2d(2000)

[-1.0842714164403664, 3.536430677617829]
[-1.5192611589877676, 3.2087853857576385]
[-0.5837238321084257, 0.14118852451559077]
[2.6881587327790375, 0.16835671038884836]
[1.9047058016540412, 1.3708147600108693]
[2.186070333709686, 1.5333415360326152]
[2.5264132006001803, 3.924037956311918]
[2.6540945253370465, 0.7507464377944795]
[1.9219981696914759, 1.8036241505540422]
[3.2803915345990693, 1.3363319377298986]
[3.432992730299137, 0.5139712582089148]
[3.7161967297710508, 3.469136660595091]
[3.642625250111134, 1.7138386664223049]
[2.20111006309949, -0.023361368263659976]
[5.005538037949205, -0.07451385607195504]
[3.9099271720645503, -0.7611428763452311]
[2.3407016974738513, 0.6013280985013257]
[2.598812630210536, 2.7662522460071943]
[3.7933470996980776, 0.0664638944366151]
[4.827669996730764, 0.8560049817668363]
[1.7979522063186673, -2.3816754101377793]
[4.860904328692774, 0.46512760846150847]
[3.6529023730945824, 0.2765460726654271]
[3.9065937331547347, -1.4385970370281558]
[5.15975025648

[array([0.56873002, 3.69242436]),
 array([0.56873002, 3.69242436]),
 array([0.04512028, 3.29806084]),
 array([0.06318026, 4.58357781]),
 array([0.79717544, 4.4266318 ]),
 array([0.79717544, 4.4266318 ]),
 array([0.79717544, 4.4266318 ]),
 array([0.79717544, 4.4266318 ]),
 array([0.79717544, 4.4266318 ]),
 array([0.79717544, 4.4266318 ]),
 array([0.79717544, 4.4266318 ]),
 array([-0.07679213,  5.37144284]),
 array([-0.07679213,  5.37144284]),
 array([-0.07679213,  5.37144284]),
 array([-0.07679213,  5.37144284]),
 array([0.15827873, 4.54499011]),
 array([0.15827873, 4.54499011]),
 array([0.15827873, 4.54499011]),
 array([0.15827873, 4.54499011]),
 array([0.15827873, 4.54499011]),
 array([0.15827873, 4.54499011]),
 array([0.15827873, 4.54499011]),
 array([0.26619255, 4.55008649]),
 array([0.34403654, 3.33561853]),
 array([0.34403654, 3.33561853]),
 array([0.85877762, 3.52735694]),
 array([0.13999355, 3.8033859 ]),
 array([0.13999355, 3.8033859 ]),
 array([0.13999355, 3.8033859 ]),
 array